---
title: "Nobel Prize in Economic Sciences 2022"
author: ''
date: '2022-10-17'
slug: week-7
categories: []
tags: []
---

## The Prize in Economic Sciences 2022

[10 October 2022](/pdf/press-economicsciencesprize2022.pdf)

The Royal Swedish Academy of Sciences has decided to award the Sveriges Riksbank Prize in Economic Sciences in Memory of Alfred Nobel 2022 to

**Ben S. Bernanke**
The Brookings Institution, Washington DC, USA

born 1953 in Augusta, GA, USA. PhD 1979 from Massachusetts Institute of Technology, Cambridge, USA. Distinguished Senior Fellow, Economic Studies, The Brookings Institution, Washington DC, USA.

**Douglas W. Diamond**
University of Chicago, IL, USA

born 1953. PhD 1980 from Yale University, New Haven, CT, USA. Merton H. Miller Distinguished Service Professor of Finance, University of Chicago, Booth School of Business, IL, USA.


**Philip H. Dybvig**
Washington University in St. Louis, MO, USA

born 1955. PhD 1979 from Yale University, New Haven, CT, USA. Boatmen’s Bancshares Professor of Banking and Finance, Washington University in St. Louis, Olin Business School, MO, USA.

*“for research on banks and financial crises”*

**Prize amount**: 10 million Swedish kronor, to be shared equally between the laureates.

## Illustrations

Illustration: [The prize in economic sciences 2022](/image/press-economicsciencesprize2022-figure1a.pdf)

Illustration: [Bank run (pdf)](/image/press-economicsciencesprize2022-figure1.pdf)

Illustration: [Maturity transformation (pdf)](/image/press-economicsciencesprize2022-figure2.pdf)

Illustration: [Loan loss (pdf)](/image/press-economicsciencesprize2022-figure3.pdf)

## Read more about this year’s prize

[Popular science background: The laureates explained the central role of banks in financial crises (pdf)](/pdf/popular-economicsciencesprize2022.pdf)

[Scientific Background: Financial intermediation and the economy (pdf)](/pdf/advanced-economicsciencesprize2022-2.pdf)

## Video

- [Prize announcement](https://www.youtube.com/watch?v=tJhbHt5zX5o&t=41s)

- [Interview about the awarded work](https://www.youtube.com/watch?v=rQu-R7epxdM&t=148s)


<!-- ## What have we covered this week? -->

<!-- - [Kelvin's Presentation about BING](/pdf/Presentation Microsoft Bing_Kelvin.pdf) -->

<!-- - [Case Study 1.2: AMAZON](/pdf/case_study_2.pdf) -->

<!-- - [Price Discrimination on Line](/pdf/PriceDiscriminationOnLine.pdf) -->

<!-- - [Shiller's Paper](/pdf/Shiller - Approximating Purchase Propensities and Reservation Prices from Broad Consumer Tracking.pdf) -->


<!-- ## Video Link -->

<!-- Video recording of lecture is available at [here](https://ksu.zoom.us/rec/play/WhJG9Yzh2oHQ0etSPXfP_9PBd0SJbL3rSNYm4_WmrM61gzdfBrTs-dhEGTVDKsVZdLxhblcnY41pi8Mr.KmbLy0ksfxEcI_5k?continueMode=true&_x_zm_rtaid=Y8Wh0dHdRjyZVSG90zjOeQ.1666064580079.e557f76a066d79ec5ead26a407f8c983&_x_zm_rhtaid=893) -->